model:
  num_layers: 101
  image_size: [384, 384]
  num_joints: 17
  deconv_with_bias: false
  num_deconv_layers: 3
  num_deconv_filters: [256, 256, 256]
  num_deconv_kernels: [4, 4, 4]
  final_conv_kernel: 1
  heatmap_size: [96, 96]
  restore: /running_package/pose_resnet_101_384x384.tar
data:
  input: /running_package/cropped
  output: /job_data
  test_all: /running_package/test_all_cropped
training:
  epochs: 8
  batch_size: 256
  val_interval: 500
  print_interval: 50
  n_workers: 8
testing:
  save: True
seeds: 1333

  



  